on: push
name: AsciiDoc GitHub Pages
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          asciidoctor_params: --attribute=nofooter
          pdf_build: true
